### ISSUE TITLE
Laser cutter calendar redirect 

### ISSUE THREAD

**Issue by gbowman85** [DoESLiverpool/wiki#1]
The page at https://doesliverpool.com/laser-cutter-calendar/ seems to be redirecting to the youcanbookme page after the page has loaded. I can see the calendar for a brief times but not looking enough to check the schedule unless I cancel the page loading before it can redirect.

**Comment by DefProc** [comment]
Confirmed, I can see that on mobile too. 

A quick look suggests that it's the iframe trying to break out when it's too small: http://knb.owwwlab.com/forums/topic/iframe-andor-pop-up-options-with-youcanbook-me/

adding `sandbox="allow-same-origin allow-scripts allow-popups allow-forms"` to the youcanbook.me iframe attributes seems to have solved it, and I've also removed the annoying `onLoad` function so it won't interfere with page position either.
